// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyColGSdw4WCkQQS0OypVhJwonaPLX5Mpxo',
    appId: '1:423487594760:web:3b9fce40eeb2679f284cbd',
    messagingSenderId: '423487594760',
    projectId: 'sahabatair-a1874',
    authDomain: 'sahabatair-a1874.firebaseapp.com',
    storageBucket: 'sahabatair-a1874.appspot.com',
    measurementId: 'G-S6LPTE1S03',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBqeJyy6MgeuC8pxrQeRHSXAGTDvIVNWF8',
    appId: '1:423487594760:android:c2217011d250dbf0284cbd',
    messagingSenderId: '423487594760',
    projectId: 'sahabatair-a1874',
    storageBucket: 'sahabatair-a1874.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBhn3T51lzHrAYFCvnGbnQ8_D8IB2qAm_Y',
    appId: '1:423487594760:ios:956b3ff88892a72b284cbd',
    messagingSenderId: '423487594760',
    projectId: 'sahabatair-a1874',
    storageBucket: 'sahabatair-a1874.appspot.com',
    iosBundleId: 'com.example.sahabatAir',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBhn3T51lzHrAYFCvnGbnQ8_D8IB2qAm_Y',
    appId: '1:423487594760:ios:956b3ff88892a72b284cbd',
    messagingSenderId: '423487594760',
    projectId: 'sahabatair-a1874',
    storageBucket: 'sahabatair-a1874.appspot.com',
    iosBundleId: 'com.example.sahabatAir',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyColGSdw4WCkQQS0OypVhJwonaPLX5Mpxo',
    appId: '1:423487594760:web:73c4a9042f6a1515284cbd',
    messagingSenderId: '423487594760',
    projectId: 'sahabatair-a1874',
    authDomain: 'sahabatair-a1874.firebaseapp.com',
    storageBucket: 'sahabatair-a1874.appspot.com',
    measurementId: 'G-HWQFBMN05L',
  );

}